### ISSUE TITLE
兼容下3.0.4可好，谢谢

### ISSUE THREAD

**Issue by stytooldex** [plain-dev/EditAdapter#1]
com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.4

**Comment by plain-dev** [comment]
@stytooldex 

你好 🎉

已兼容 `Android X` 以及 `BaseRecyclerViewAdapterHelper 3.0.4`

```
implementation 'com.github.plain-dev:EditAdapter:1.0.6-stable'
```

**Comment by stytooldex** [comment]
> @stytooldex
> 
> • 🎉
> 
> 已兼容 以及`Android X``BaseRecyclerViewAdapterHelper 3.0.4`
> 
> ```
> implementation 'com.github.plain-dev:EditAdapter:1.0.6-stable'
> ```

不错，👍 有机会，可以帮你推荐
